### ISSUE TITLE
[Feature request] 2022.x support

### ISSUE THREAD

**Issue by KaKi87** [ChrisCarini/git-push-reminder-jetbrains-plugin#2]

**Comment by ChrisCarini** [comment]
Hi @KaKi87 - just a heads up, this should be coming shortly (in https://github.com/ChrisCarini/git-push-reminder-jetbrains-plugin/commit/41ba533fa80bb3dfb59fea0c30a84837ef305656 commit; just uploaded to the JetBrains marketplace, should be about 2 business days for JetBrains before they accept/release it to the marketplace). Thank you again for opening this issue!
