### ISSUE TITLE
[Feature request] 2022.3.x support

### ISSUE THREAD

**Issue by KaKi87** [ChrisCarini/git-push-reminder-jetbrains-plugin#59]
Thanks

**Comment by ChrisCarini** [comment]
Hi @KaKi87 - thanks for the feature request!

Just to confirm, do you mean `2023.x`, which is not yet released (and, based on my guestimate, will be released in about 4 months time), or do you mean `2022.3.x`, which has been out for just over a month?

**Comment by KaKi87** [comment]
Oops, I meant `2022.3.x` 😅

**Comment by ChrisCarini** [comment]
No problem! I just released `0.1.0`, which should work with `2022.3`. Please feel free to install/update and let me know if you have any issues.

In the mean time, I'll close out this issue!
