### ISSUE TITLE
[Feature request] Change project closing behavior

### ISSUE THREAD

**Issue by KaKi87** [ChrisCarini/git-push-reminder-jetbrains-plugin#8]
Hello,

Currently :
- When a project contains unpushed commits, a warning is shown ;
- When "prevent closing project" is checked, closing the warning will always keep the project open ;
- When "prevent closing project" is unchecked, closing the warning will always close the project ;

What I recommend (option A) :
- Remove the "prevent closing project" setting ;
- Replace the "Please push before closing!" injunction with a "Would you like to close the project anyway?" question ;
- Close the project when the primary `OK` button is clicked or when the `Enter` key is pressed ;
- Keep the project open when a new secondary `Cancel` button is clicked, or when the `Esc` key is pressed, or when the top-right close button is clicked ;

Or do the opposite (option B) :
- Remove the "prevent closing project" setting ;
- Keep the injunction ;
- Keep the project open when the primary `OK` button is clicked, or when the `Enter` key is pressed ;
- Close the project when a new secondary `No` button is clicked, or when the `Esc` key is pressed, or when the top-right close button is clicked ;

Or allow both options, and eventually migrate users who checked the "prevent closing project" setting to option B, and the users who didn't to option A.

Thanks

**Comment by ChrisCarini** [comment]
Hi @KaKi87 - this is a great suggestion, thank you for submitting it.

Option A seems like a better UX in my opinion, so let's proceed with that one.

How does something like this look?
<img width="486" alt="Screen Shot 2022-07-30 at 00 14 16" src="https://user-images.githubusercontent.com/6374067/181879498-1e6c21d8-c655-4aaa-9b16-7d799daea379.png">

As you suggested, hitting <kbd>Enter</kbd> will proceed to allow the project to close, and hitting <kbd>Esc</kbd> will prevent the project from closing (ie, keep it open). Of course, clicking on the respective buttons do as you would expect. I opted to not have just "OK" and "Cancel" buttons for explicitness of behavior.

I will have a PR up shortly, if you would like to review it, that would be great! If I don't hear back from you in a few days, I will assume you have no interest in reviewing the PR and proceed to merge & release a version with this change. Let me know either way!

**Comment by KaKi87** [comment]
Hey,

This is perfect !

I'm not qualified for code review, if that's what you meant.

Thanks

**Comment by ChrisCarini** [comment]
> I'm not qualified for code review, if that's what you meant.

You're more qualified than you may think ;)

I'll go ahead and merge it in then, but you can totally take a look at the PR; a quick breakdown:

1. `GitPushReminder.java` is simply
    1. changing the dialog type (from `messageDialog` to `OkCancelDialog`),
    2. the text of buttons and icon
    3. checking if the user clicked 'ok' (ie, `close anyway`) or not
2. `SettingsConfigurable.java` and `SettingsManager.java` is simply removing the `"prevent closing project"` option
3. `*.properties` are just user-facing string properties; the two files are identical

**Comment by KaKi87** [comment]
Got it, thanks !

PS: I just noticed that you're an engineer at LinkedIn, so firstly I'm flattered by your consideration of me, secondly, may I ask how does Microsoft take that you prefer JetBrains IDEs over Visual Studio ?

**Comment by ChrisCarini** [comment]
No problem.

> ...how does Microsoft take that you prefer JetBrains IDEs over Visual Studio ?

Not sure, I have not directly asked them this question ;) That being said, most tech companies would prefer their employees are as productive as possible; sometimes that means using different tools (ie, IDEs) for various things. I likely can't comment on any specifics, of course, but I know that I am not the only engineer using a JetBrains IDE.

**Comment by ChrisCarini** [comment]
@all-contributors please add @KaKi87 for ideas
